### ISSUE TITLE
Change Todo Status

### ISSUE THREAD

**Issue by harshil1712** [MLH-Fellowship/relay-examples#17]
Acceptance Criteria
- [ ] A checkbox to change the status 
- [ ] The UI should change
- [ ] The status of the todo should toggle
