### ISSUE TITLE
Delete Todo

### ISSUE THREAD

**Issue by harshil1712** [MLH-Fellowship/relay-examples#7]
**Acceptance**
 - [ ] A button to delete the todo item
 - [ ] On clicking the button, the item should be deleted
 - [ ] The item should no longer be displayed
