### ISSUE TITLE
Create UI for the example todo app

### ISSUE THREAD

**Issue by SiddharthSham** [MLH-Fellowship/relay-examples#8]
Acceptance:
 - [x] Display all todos
 - [x] Should be responsive
 - [x] Choose views (all/todo/completed)
 - [x] Mark all as done
 - [x] Delete todos
 - [x] Update todos
